### ISSUE TITLE
[FEATURE] Add Splash screen for Drifty GUI

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Drifty#280]
### Is your feature request related to a problem? Please describe.

When Drifty GUI is launched for the very first time, the initialization time takes about 30-40 seconds on an average computer. The users will most likely think that the app has failed to start, which is not the truth. 
The latest build of Drifty GUI (v2.0.0) takes 30 seconds to start for the very first time on my computer. It does many things within this time - it creates a config directory, moves yt-dlp there and checks for any update to yt-dlp (a component of Drifty).

### Describe the solution you'd like.

A transparent splash screen showing the progress of the initialization would be better. The splash screen should also contain the version number of Drifty along with a progress bar. The main part of the splash screen can look like this -

![Image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/58d84290-4f73-48ab-ae1a-740495e55a7e)

### Screenshots

The time it takes to open Drifty GUI screen can be seen from this video -

https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/43bf7e95-b1cd-4f85-b13f-166078b22d96

### Additional information

If anyone wish to work on this issue, please comment below and I will assign you with the task.

**Comment by mohiyaddeen7** [comment]
i would like to work on this @SaptarshiSarkar12

**Comment by SaptarshiSarkar12** [comment]
@mohiyaddeen7 Sure, you can work on it. Assigning the task to you :+1:.

**Comment by mohiyaddeen7** [comment]
i am new to contribution. please guide me.

**Comment by SaptarshiSarkar12** [comment]
> i am new to contribution. please guide me.

Sure, I can help you. Can you please tell me what problems are you facing? Did you understand what is the issue trying to say?

**Comment by SaptarshiSarkar12** [comment]
@mohiyaddeen7 If you wish, you can discuss your problem in [our Discord server](https://discord.gg/DeT4jXPfkG).

**Comment by mohiyaddeen7** [comment]
i have to implement a suspense screen  for the application right?

**Comment by mohiyaddeen7** [comment]
which ide to use for working on this issue?

**Comment by SaptarshiSarkar12** [comment]
> i have to implement a suspense screen for the application right? @SaptarshiSarkar12

What do you mean by `suspense screen`? You are supposed to add a **Splash Screen** which means a screen which will open up initially showing the progress of the initialization.

**Comment by SaptarshiSarkar12** [comment]
You are going to use [**IntelliJ Idea**](https://www.jetbrains.com/idea/)

**Comment by mohiyaddeen7** [comment]
> > i have to implement a suspense screen for the application right? @SaptarshiSarkar12
> 
> What do you mean by `suspense screen`? You are supposed to add a **Splash Screen** which means a screen which will open up initially showing the progress of the initialization.

yes. got it.

**Comment by SaptarshiSarkar12** [comment]
@mohiyaddeen7 How much is done? Did you start working on it? did you face any problem?

**Comment by SaptarshiSarkar12** [comment]
@mohiyaddeen7 Please tell me about your progress in this issue.

**Comment by SaptarshiSarkar12** [comment]
@mohiyaddeen7 Do you still wish to work on this issue? You seem to be inactive for a long period of time.

**Comment by adesh1998** [comment]
Could you please assign issue to me?

**Comment by SaptarshiSarkar12** [comment]
Yes, @adesh1998 you can work on this issue 👍.

**Comment by adesh1998** [comment]
could you help me understand why Drifty is failing for docker compose command :
failed to solve: drifty-runner:latest: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 What was the exact command you used which got this error? Is it `docker compose run gui`?

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 I re-run the `docker compose run gui` command in my machine and there was no error. Which command did you try?

![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/42467dd8-8f45-4ba6-930b-531c4095fe75)

**Comment by SaptarshiSarkar12** [comment]
And, it successfully runs `Drifty GUI` :point_down: 
![image](https://github.com/SaptarshiSarkar12/Drifty/assets/105960032/3bcc187e-226d-4aa8-9f6f-642ee29c085c)

**Comment by adesh1998** [comment]
Do I need to change anything in docker file to run it on macbook:
I am getting below error after running docker compose run gui:
 > [gui build 5/5] RUN mvn -Pbuild-drifty-gui-for-ubuntu-latest gluonfx:build gluonfx:package:
0.097 qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
------
failed to solve: process "/bin/sh -c mvn -Pbuild-drifty-gui-for-ubuntu-latest gluonfx:build gluonfx:package" did not complete successfully: exit code: 255

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 I think you are having Apple Silicon Mac with ARM64 architecture.
Please try changing the **Dockerfile** in `Docker/dev/commons/base` directory to :point_down: 
```dockerfile
FROM --platform=linux/amd64 debian:bookworm-slim

WORKDIR /build

COPY ./config /build/config
RUN apt-get update -y

RUN apt-get install gcc build-essential -y && \
    apt-get install wget tar gzip -y && \
    apt-get install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libfreetype6-dev \
    libgl-dev libglib2.0-dev libgtk-3-dev libpango1.0-dev libx11-dev libxtst-dev zlib1g-dev -y --no-install-recommends &&\
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Download and install Maven 3.8.8 GraalVM
RUN wget https://apache.osuosl.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz && \
    wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-20.0.2/graalvm-community-jdk-20.0.2_linux-x64_bin.tar.gz && \
    tar -xzf apache-maven-3.8.8-bin.tar.gz && \
    tar -xzf graalvm-community-jdk-20.0.2_linux-x64_bin.tar.gz &&\
    rm apache-maven-3.8.8-bin.tar.gz && \
    rm graalvm-community-jdk-20.0.2_linux-x64_bin.tar.gz

# Setting environment variables
ENV PATH="/build/apache-maven-3.8.8/bin:$PATH"
ENV JAVA_HOME="/build/graalvm-community-openjdk-20.0.2+9.1"
ENV GRAALVM_HOME="/build/graalvm-community-openjdk-20.0.2+9.1"
ENV PATH="/build/graalvm-community-openjdk-20.0.2+9.1/bin:$PATH"
```
And, also change the **Dockerfile** in `Docker/dev/commons/runner` directory to :point_down: 
```dockerfile
FROM --platform=linux/amd64 python:3.11-slim as runner

RUN apt-get update --no-install-recommends && apt-get install ffmpeg libsm6 libxext6 libgtk-3-0 -y --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
```
Then, re-try. It should work now. Let me know if that worked.

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 Did the above solution work for you?

**Comment by adesh1998** [comment]
@SaptarshiSarkar12 still facing same issue:
<img width="1427" alt="Screenshot 2023-11-19 at 10 57 06 PM" src="https://github.com/SaptarshiSarkar12/Drifty/assets/50673082/9ba047c2-59a7-4315-8c8d-4b030ebc6e23">

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 Can you please run `docker rmi $(sudo docker images -q) --force` before the `docker compose up` command and try again?

**Comment by xma08** [comment]
you may also need to specify platform in the `Docker/dev/GUI/Dockerfile` for your M chip,
```
FROM --platform=linux/amd64 drifty-base:latest AS build
# Set the working directory
WORKDIR /app

COPY . .

RUN gcc -c /app/config/missing_symbols.c -o /app/config/missing_symbols-ubuntu-latest.o

RUN mvn -Pbuild-drifty-gui-for-ubuntu-latest gluonfx:build gluonfx:package

FROM --platform=linux/amd64 drifty-runner:latest
WORKDIR /app
COPY --from=build /app/target/gluonfx/x86_64-linux /app

CMD [ "/app/Drifty" ]
```

**Comment by SaptarshiSarkar12** [comment]
@xma08 Yeah, thanks for pointing out :smile:! You're right :+1:. It should work now.
@adesh1998 Can you please try with the changes as mentioned by @xma08 and let us know if it worked :grin:?

**Comment by xma08** [comment]
hmm, I passed the build but failed when bootstraping. any idea?
```
Nov 23, 2023 7:24:35 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Nov 23, 2023 7:24:35 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ca8564a'
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:164)
        at java.base@20.0.2/java.security.AccessController.executePrivileged(AccessController.java:171)
        at java.base@20.0.2/java.security.AccessController.doPrivileged(AccessController.java:319)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
        at com.sun.glass.ui.Application.run(Application.java:146)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
        at java.base@20.0.2/java.lang.Thread.runWith(Thread.java:1636)
        at java.base@20.0.2/java.lang.Thread.run(Thread.java:1623)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```

**Comment by adesh1998** [comment]
@SaptarshiSarkar12  I am also getting same error as @xma08

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 @xma08 Yeah, that's a known error. This error has already been mentioned implicitly in the README. Please read [this](https://github.com/SaptarshiSarkar12/Drifty/blob/master/Docker/macOS%20Docker%20Build%20Instructions.md). It contains a detailed guide with images, to solve this issue.
Please let me know if that worked 🙂.

**Comment by xma08** [comment]
Thanks. I followed the instruction by configuring manual IP address and XQuartz. In the last step running, `socat` threw an error when `docker compose run`.
```
❯ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"&
open -a Xquartz
docker compose run -e DISPLAY=192.168.1.10:0 gui
[1] 46565
[+] Building 0.0s (0/0)                                                                           docker:desktop-linux
[+] Creating 2/0
 ✔ Container drifty-runner  Created                                                                               0.0s
 ✔ Container drifty-base    Created                                                                               0.0s
[+] Running 2/2
 ✔ Container drifty-runner  Started                                                                               0.2s
 ✔ Container drifty-base    Started                                                                               0.2s
[+] Building 0.0s (0/0)                                                                           docker:desktop-linux
Nov 24, 2023 1:02:41 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Nov 24, 2023 1:02:41 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ca8564a'
2023/11/24 07:02:41 socat[46571] E UNIX-CLIENT: : Invalid argument
                                                                  2023/11/24 07:02:41 socat[46572] E UNIX-CLIENT: : Invalid argument
             Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:164)
	at java.base@20.0.2/java.security.AccessController.executePrivileged(AccessController.java:171)
	at java.base@20.0.2/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base@20.0.2/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20.0.2/java.lang.Thread.run(Thread.java:1623)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```

**Comment by xma08** [comment]
Thanks. I followed the instruction by configuring manual IP address and XQuartz. In the last step running, `socat` threw an error when `docker compose run`.
```
❯ socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"&
open -a Xquartz
docker compose run -e DISPLAY=192.168.1.10:0 gui
[1] 46565
[+] Building 0.0s (0/0)                                                                           docker:desktop-linux
[+] Creating 2/0
 ✔ Container drifty-runner  Created                                                                               0.0s
 ✔ Container drifty-base    Created                                                                               0.0s
[+] Running 2/2
 ✔ Container drifty-runner  Started                                                                               0.2s
 ✔ Container drifty-base    Started                                                                               0.2s
[+] Building 0.0s (0/0)                                                                           docker:desktop-linux
Nov 24, 2023 1:02:41 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.
Nov 24, 2023 1:02:41 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @6ca8564a'
2023/11/24 07:02:41 socat[46571] E UNIX-CLIENT: : Invalid argument
                                                                  2023/11/24 07:02:41 socat[46572] E UNIX-CLIENT: : Invalid argument
             Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
	at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:164)
	at java.base@20.0.2/java.security.AccessController.executePrivileged(AccessController.java:171)
	at java.base@20.0.2/java.security.AccessController.doPrivileged(AccessController.java:319)
	at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:162)
	at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
	at com.sun.glass.ui.Application.run(Application.java:146)
	at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
	at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base@20.0.2/java.lang.Thread.runWith(Thread.java:1636)
	at java.base@20.0.2/java.lang.Thread.run(Thread.java:1623)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:210)
```

**Comment by SaptarshiSarkar12** [comment]
@xma08 Now, this is unexpected :cry:.
Can you please try `docker compose run -e DISPLAY=$DISPLAY --net=host gui`?

**Comment by SaptarshiSarkar12** [comment]
@xma08 XQuartz should be running in the background when you are working on the docker image. Let me know if this worked :smile:.

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 @xma08 Did it work?

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 Are you working on this issue? You seem to be inactive for a long time.

**Comment by adesh1998** [comment]
Sorry i was busy. I will unassign myself

**Comment by SaptarshiSarkar12** [comment]
@adesh1998 It's okay. Then, I'll work on this :grin:.
